### PR TITLE
Revert "Implement get_parents and get_children on Source for UUID generation"

### PR DESCRIPTION
**Pull request by sbuss**
This reverts commit 438a9c8eff7bad83c8414a720eb7da27c4e1ba72, which broke PTS/PPTS links

### CODE REVIEW

**Comment by ilakyapal** [comment]
Looks like the test fails? Do you need to rerun gen-test-data?

**Comment by sbuss** [comment]
In this case, the test is correctly failing because reverting this means `PTS.planning_case_number` values are being ignored

**Comment by ilakyapal** [comment]
So if you look at the error, the planning_case_number values for MOHCD are being ignored (which means that the expected mohcd children for a given node won't be retrieved) like you said which makes sense... but it looks like the GPR is also missing from the list... which doesn't make any sense to me because as far as I can tell none of the logic that we reverted should affect the parent/child relationships among PPTS records... Any thoughts here?

**Comment by ilakyapal** [comment]
Ok so I think that the current graph logic is actually just assigning the wrong UUID to the GPR. I'll file an issue to fix it. 

The reason this test was passing in the previous PR was actually not because the GPR was in the list of ppts children, but because the "building_permit_number" was in the list, and we were simply comparing the lengths of lists which is why we didn't catch it.

**Comment by ilakyapal** [comment]
Filed the issue here: https://github.com/sfcpc/housing-dashboard/issues/46

**Pull request merged**
